### ISSUE TITLE
Needs to be idempotent

### ISSUE THREAD

**Issue by rigareau** [voxpupuli/puppet-sslcertificate#22] opened 2016-06-21 19:05 UTC
From what I can see in the execution reports.  
This module trying to install my cert in every run.
It should verify prior to installation if the certificate is already present in the destination store.

**Comment by rigareau** [comment] 2016-06-21 19:22
Oups, corrected

**Comment by wottah** [comment] 2017-09-18 09:04
I have this same issue on windows 2008 R2. Is anyone looking into this?

**Comment by igalic** [comment] 2017-09-20 15:25
inexplicably, i have gotten a notification from this issue. does anyone know if this is still a thing?

**Comment by cmezzett** [comment] 2018-03-06 15:30
Seems to be a duplicate of issue 33, I've submitted a PR for that

**Comment by ghoneycutt** [comment] 2019-12-28 22:54
This seems to have been fixed by #70

**Closed by ghoneycutt** 2019-12-28 22:54 UTC
